routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Http\Request;


Route::get('/test2', "TelegramBotController@getUpdates");
Route::get('/test3', function (Request $request) {
    $user = \App\Models\User::where('email', 'putalexey@redlg.ru')->first();
    return response($user->getBotAddingUrl());
//    var_dump($_method->getDocComment());
//    var_dump(Telegram::sendMessage([
//        'chat_id' => 260019765,
//        'text' => 'test sending message'
//    ]));
});
Route::get('/test', function (Request $request) {
    echo "<form method='post'>
        " . csrf_field() . "
        <input type='submit' value='шаг'>
        </form>";

    echo "<div style='display: flex;'>";
        echo "<pre style='max-width: 50%;overflow: auto;'>";
        echo json_encode(
            \App\Models\ChatState::where('user_id', Auth::user()->id)
                ->without(['user', 'workflow.steps'])->first(),
                JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE
        );
        echo "</pre>";
        echo "<pre style='max-width: 50%;overflow: auto;'>";
        echo json_encode(
            \App\Models\ChatStatesHistory::where('user_id', Auth::user()->id)
                ->with(['chat', 'workflow', 'workflow_step'])
                ->without(['workflow.steps'])
                ->orderBy('id', 'desc')->limit(1)->offset(1)
                ->without(['workflow.steps'])->first(),
                JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE
        );
        echo "</pre>";
    echo "</div>";
});
Route::post('/test', function (Request $request) {
    \Carbon\Carbon::setTestNow(\Carbon\Carbon::now()->addDay());
//    $state = \App\Models\ChatState::where('chat_state', \App\Models\ChatState::STATE_STOPPED)->where('user_id', Auth::user()->id)->first();
    $state = \App\Models\ChatState::where('chat_state', "!=", \App\Models\ChatState::STATE_STOPPED)->where('user_id', Auth::user()->id)->first();
    if ($state)
        dispatch((new \App\Jobs\ProcessChatState($state))->onConnection('sync'));

    return back();
});
Route::get('/', function (Request $request) {
    $price = $request->get("option") == '09ea221d3db11df1f369094ffb4bda7c' ? '16900' : '9900';
    return view('landing', ["price" => $price]);
});
Route::any('/chat/', 'LandingChatController@index');
Route::get('/chat/email/', 'LandingChatController@getOurEmail');
Route::post('/chat/save/', 'LandingChatController@save');

// управление ботом
Route::group(['prefix' => 'bot'], function () {
    Route::post('webhook/{token}', 'TelegramBotController@webhook');
    Route::group(['middleware' => 'can:admin-bot'], function() {
        Route::get('/', 'TelegramBotController@index')->name('bot.index');
        Route::get('webhook', 'TelegramBotController@getWebhookInfo')->name('bot.webhook');
        Route::post('test', 'TelegramBotController@ping')->name('bot.ping');
        Route::post('init', 'TelegramBotController@sendCertificate')->name('bot.init');
    });
});


Auth::routes();
Route::group(["middleware" => 'auth' ], function() {
//    Route::get('/workflows/{workflow_id}/steps', "WorkflowController@steps");
    Route::get('/lk/', function (Request $request) {
        $sections = \App\Models\Section::ordered()
            ->with(['assignments', 'assignments.tasks'])
            ->get();
        $answers = \App\Models\TaskAnswer::where('user_id', Auth::user()->id)->get()->keyBy('task_id');
        return view('cabinet.assignments', [
            "sections" => $sections,
            "answers" => $answers,
        ]);
    })->name('cabinet');
    Route::put('workflow/{workflow}/step_path', "WorkflowController@step_path")->name('workflow.step_path');
    Route::post('workflow/{workflow}/steps/{step}/file', "WorkflowStepsController@uploadFile")->name('workflow.steps.file.upload');
    Route::delete('workflow/{workflow}/steps/{step}/file/{file}', "WorkflowStepsController@deleteFile")->name('workflow.steps.file.delete');

    Route::get('assignment', "AssignmentController@all")->name('assignment.all');
    Route::resource('section', "SectionController");
    Route::resource('section.assignment', "AssignmentController");
    Route::resource('section.assignment.task', "TaskController");

    Route::resource('workflow', "WorkflowController");
    Route::resource('workflow.steps', "WorkflowStepsController", [
        'except' => ['create', 'show', 'edit',]
    ]);
});

Route::get('/home', 'HomeController@index');

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Traits\GeneratesSelectPositions;
use App\Http\JSONReponse;
use App\Models\Assignment;
use App\Models\Section;
use App\Models\Task;
use Illuminate\Http\Request;

class TaskController extends Controller
{
    use GeneratesSelectPositions;

    /**
     * Display a listing of the resource.
     *
     * @param $section_id
     * @param Assignment $assignment
     * @return \Illuminate\Http\Response
     */
    public function index($section_id, Assignment $assignment)
    {
        return view('task.index', [
            'section_id' => $section_id,
            'assignment' => $assignment,
            'tasks' => $assignment->tasks()->ordered()->get(),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param $section_id
     * @param Assignment $assignment
     * @return \Illuminate\Http\Response
     */
    public function create($section_id, Assignment $assignment)
    {
        $task = new Task();
        $select_positions = $this->getSelectPositions($assignment->tasks()->ordered()->get(), $task);
        $task->position = $select_positions->keys()->last();
        return view('task.edit', [
            'section_id' => $section_id,
            'assignment' => $assignment,
            'select_positions' => $select_positions,
            'task' => $task,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param $section_id
     * @param $assignment_id
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $section_id, $assignment_id)
    {
        $task = new Task($request->all());
        $task->assignment_id = $assignment_id;
        $task->save();
        Task::updatePositions();

        return redirect(route('section.assignment.task.index', [$section_id, $assignment_id]));
    }

    /**
     * Display the specified resource.
     *
     * @param $section_id
     * @param $assignment_id
     * @param $task_id
     * @return \Illuminate\Http\Response
     * @internal param Task $task
     */
    public function show($section_id, $assignment_id, $task_id)
    {
        return JSONReponse::redirect(route('section.assignment.task.index', [$section_id, $assignment_id, $task_id]));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param $section_id
     * @param Assignment $assignment
     * @param  \App\Models\Task $task
     * @return \Illuminate\Http\Response
     */
    public function edit($section_id, Assignment $assignment, Task $task)
    {
        $select_positions = $this->getSelectPositions($assignment->tasks()->ordered()->get(), $task);
        return view('task.edit', [
            'section_id' => $section_id,
            'assignment' => $assignment,
            'select_positions' => $select_positions,
            'task' => $task,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $section_id, $assignment_id, Task $task)
    {
        $task->update($request->all());
        Task::updatePositions();

        return JSONReponse::redirect(route('section.assignment.task.index', [$section_id, $assignment_id, $task->id]));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function destroy($section_id, $assignment_id, Task $task)
    {
        $task->delete();

        return JSONReponse::redirect(route('section.assignment.task.index', [$section_id, $assignment_id, $task->id]));
    }
}

resources/views/task/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <a href="{{ route('section.assignment.task.index', [$section_id, $assignment->id]) }}" class="btn-link">← К списку</a>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        @if($task->exists)
                            Изменение задания
                        @else
                            Добавление задания
                        @endif
                    </div>
                    <div class="panel-body">
                        <form class="form-horizontal"
                              role="form" method="POST"
                              action="{{ $task->exists ? route('section.assignment.task.update', [$section_id, $assignment->id, $task->id]) : route('section.assignment.task.store', [$section_id, $assignment->id]) }}">
                            {{ csrf_field() }}
                            {{ $task->exists ? method_field('PUT') : "" }}
                            <input type="hidden" name="assignment_id" value="{{ $assignment->id }}">

                            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                                <label for="name" class="col-md-4 control-label">Заголовок</label>
                                <div class="col-md-6">
                                    <input type="text" id="name" class="form-control" name="name" value="{{ old('name', $task->name) }}" />
                                    @if ($errors->has('name'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('text') ? ' has-error' : '' }}">
                                <label for="text" class="col-md-4 control-label">Описание в личном кабинете</label>
                                <div class="col-md-6">
                                    <textarea id="text" name="text" class="form-control">{{ old('text', $task->text) }}</textarea>
                                    @if ($errors->has('text'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('text') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('chat_text') ? ' has-error' : '' }}">
                                <label for="text" class="col-md-4 control-label">Описание для чата</label>
                                <div class="col-md-6">
                                    <textarea id="text" name="text" class="form-control">{{ old('chat_text', $task->chat_text) }}</textarea>
                                    @if ($errors->has('chat_text'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('chat_text') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('position') ? ' has-error' : '' }}">
                                <label for="position" class="col-md-4 control-label">Порядок</label>
                                <div class="col-md-6">
                                    {{ \Form::select('position', $select_positions, old('position', $task->position), ['class' => 'form-control']) }}
                                    @if ($errors->has('position'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('position') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        @if($task->exists)
                                            Измененить
                                        @else
                                            Добавить
                                        @endif
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/task/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <a href="{{ route('section.assignment.index', [$section_id]) }}" class="btn-link">← К разделам</a>
                <div class="panel panel-default">
                    <div class="panel-heading">Задания упражнения "{{ $assignment->name }}"</div>
                    {{--<div class="panel-body"></div>--}}
                    <table class="table table-striped table-hover">
                        <tr>
                            <th width="50">ID</th>
                            <th>Заголовок</th>
                            <th>Текст</th>
                            <th>Порядок</th>
                            <th width="150"></th>
                        </tr>
                        @foreach($tasks as $item)
                            <tr id="task_{{ $item->id }}" class="{{ $item->active ? 'active' : '' }}">
                                <td>{{ $item->id }}</td>
                                <td>{{ $item->name }}</td>
                                <td>{{ $item->text }}</td>
                                <td>{{ $item->position }}</td>
                                <td>
                                    <a href="{{ route('section.assignment.task.edit', [$section_id, $assignment->id, $item->id]) }}"
                                       class="btn btn-xs btn-primary">изменить</a>
                                    <a href="{{ route('section.assignment.task.destroy', [$section_id, $assignment->id, $item->id]) }}"
                                       onclick="return postDelete(this, $('#task_{{ $item->id }}'))"
                                       class="btn btn-xs btn-danger">удалить</a>
                                </td>
                            </tr>
                        @endforeach
                        <tr>
                            <td colspan="5">
                                <a href="{{ route('section.assignment.task.create', [$section_id, $assignment->id]) }}" class="btn btn-primary">Добавить новый</a>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <script>
        function postDelete(link, deleteItem) {
            var url = $(link).attr('href');
            if (confirm('Уверены, что хотите удалить?')) {
                $.ajax({
                    url: url,
                    method: 'post',
                    dataType: 'json',
                    data: {
                        _method: 'delete'
                    }
                }).done(function (data) {
                    if (data.error) {
                        toastr.error(data.error);
                    } else {
                        toastr.info(data.message || 'Удалено');
                        if (deleteItem) {
                            if (!deleteItem.jquery) {
                                deleteItem = $(deleteItem);
                            }
                            deleteItem.remove();
                        }
                    }
                }).fail(function(xhr, status, error) {
                    toastr.error(error);
                });
            }
            return false;
        }
    </script>
@endsection