routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Http\Request;


Route::get('/test2', "TelegramBotController@getUpdates");
Route::get('/test3', function (Request $request) {
    $user = \App\Models\User::where('email', 'putalexey@redlg.ru')->first();
    return response($user->getBotAddingUrl());
//    var_dump($_method->getDocComment());
//    var_dump(Telegram::sendMessage([
//        'chat_id' => 260019765,
//        'text' => 'test sending message'
//    ]));
});
Route::get('/test', function (Request $request) {
    echo "<form method='post'>
        " . csrf_field() . "
        <input type='submit' value='шаг'>
        </form>";

    echo "<div style='display: flex;'>";
        echo "<pre style='max-width: 50%;overflow: auto;'>";
        echo json_encode(
            \App\Models\ChatState::where('user_id', Auth::user()->id)
                ->without(['user', 'workflow.steps'])->first(),
                JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE
        );
        echo "</pre>";
        echo "<pre style='max-width: 50%;overflow: auto;'>";
        echo json_encode(
            \App\Models\ChatStatesHistory::where('user_id', Auth::user()->id)
                ->with(['chat', 'workflow', 'workflow_step'])
                ->without(['workflow.steps'])
                ->orderBy('id', 'desc')->limit(1)->offset(1)
                ->without(['workflow.steps'])->first(),
                JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE
        );
        echo "</pre>";
    echo "</div>";
});
Route::post('/test', function (Request $request) {
    \Carbon\Carbon::setTestNow(\Carbon\Carbon::now()->addDay());
//    $state = \App\Models\ChatState::where('chat_state', \App\Models\ChatState::STATE_STOPPED)->where('user_id', Auth::user()->id)->first();
    $state = \App\Models\ChatState::where('chat_state', "!=", \App\Models\ChatState::STATE_STOPPED)->where('user_id', Auth::user()->id)->first();
    if ($state)
        dispatch((new \App\Jobs\ProcessChatState($state))->onConnection('sync'));

    return back();
});
Route::get('/', function (Request $request) {
    $price = $request->get("option") == '09ea221d3db11df1f369094ffb4bda7c' ? '16900' : '9900';
    return view('landing', ["price" => $price]);
});
Route::any('/chat/', 'LandingChatController@index');
Route::get('/chat/email/', 'LandingChatController@getOurEmail');
Route::post('/chat/save/', 'LandingChatController@save');

// управление ботом
Route::group(['prefix' => 'bot'], function () {
    Route::post('webhook/{token}', 'TelegramBotController@webhook');
    Route::group(['middleware' => 'can:admin-bot'], function() {
        Route::get('/', 'TelegramBotController@index')->name('bot.index');
        Route::get('webhook', 'TelegramBotController@getWebhookInfo')->name('bot.webhook');
        Route::post('test', 'TelegramBotController@ping')->name('bot.ping');
        Route::post('init', 'TelegramBotController@sendCertificate')->name('bot.init');
    });
});


Auth::routes();
Route::group(["middleware" => 'auth' ], function() {
//    Route::get('/workflows/{workflow_id}/steps', "WorkflowController@steps");
    Route::get('/lk/', function (Request $request) {
        $sections = \App\Models\Section::ordered()
            ->with(['assignments', 'assignments.tasks'])
            ->get();
        $answers = \App\Models\TaskAnswer::where('user_id', Auth::user()->id)->get()->keyBy('task_id');
        return view('cabinet.assignments', [
            "sections" => $sections,
            "answers" => $answers,
        ]);
    })->name('cabinet');
    Route::put('workflow/{workflow}/step_path', "WorkflowController@step_path")->name('workflow.step_path');
    Route::post('workflow/{workflow}/steps/{step}/file', "WorkflowStepsController@uploadFile")->name('workflow.steps.file.upload');
    Route::delete('workflow/{workflow}/steps/{step}/file/{file}', "WorkflowStepsController@deleteFile")->name('workflow.steps.file.delete');

    Route::get('assignment', "AssignmentController@all")->name('assignment.all');
    Route::resource('section', "SectionController");
    Route::resource('section.assignment', "AssignmentController");
    Route::resource('section.assignment.task', "TaskController");

    Route::resource('workflow', "WorkflowController");
    Route::resource('workflow.steps', "WorkflowStepsController", [
        'except' => ['create', 'show', 'edit',]
    ]);
});

Route::get('/home', 'HomeController@index');

app/Models/Workflow.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\Workflow
 *
 * @property int $id
 * @property string $name
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @property bool $main
 * @property-read \App\Models\WorkflowStep $first_step
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\WorkflowStep[] $steps
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Workflow whereMain($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Workflow whereCreatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Workflow whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Workflow whereName($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Workflow whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class Workflow extends Model
{
    protected $fillable = [
        'main',
        'name',
    ];

    protected $_first_in_tree = null;

    /**
     * @var \Illuminate\Support\Collection
     */
    protected $allSteps = null;

    /**
     * Возвращает первый шаг сценария, а последующие шаги хранится в параметре next предыдущего
     * @return WorkflowStep|null
     */
    public function steps_tree()
    {
        if(!$this->_first_in_tree) {
            $this->allSteps = $this->steps->keyBy('id');
            $this->allSteps->each(function ($step) {
//            dump($step->toArray(), $step->parent_id);
                if ($step->parent_id) {
                    if (!$this->allSteps[$step->parent_id]->next)
                        $this->allSteps[$step->parent_id]->next = collect();
                    $this->allSteps[$step->parent_id]->next[] = $step;
                } else if ($step->type == WorkflowStep::TYPE_START) {
                    $this->_first_in_tree = $step;
                }
            });
        }
        return $this->_first_in_tree;
    }

    public function first_step()
    {
        $relation = $this->hasOne(WorkflowStep::class);
        $relation->getQuery()->where('type', WorkflowStep::TYPE_START);
        return $relation;
    }

    /**
     * @param $id
     * @return WorkflowStep|null
     */
    public function getStepById($id)
    {
        $this->steps_tree();
        return $this->allSteps->get($id, null);
    }

    public function steps() {
        return $this->hasMany(WorkflowStep::class);
    }

    protected static function boot()
    {
        parent::boot();
        static::deleting(function($workflow) {
            /** @var Workflow $workflow */
            $workflow->steps()->get()->each(function($step) {
                $step->delete();
            });
        });
    }
}

app/Http/Controllers/WorkflowController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\UserField;
use App\Models\Workflow;
use App\Models\WorkflowStep;
use Illuminate\Http\Request;

class WorkflowController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $workflows = Workflow::all();
        if ($request->expectsJson()) {
            return response($workflows);
        }
        return view('workflow.index', [
            'workflows' => $workflows
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('workflow.edit', ['workflow' => new Workflow()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $workflow = new Workflow([
            "name" => $request->name
        ]);
        if ($request->get('main')) {
            Workflow::where('main', '=', '1')->update(['main' => 0]);
            $workflow->main = 1;
        }
        $workflow->save();
        // create initial step
        WorkflowStep::create([
            'workflow_id' => $workflow->id,
            'data' => new \stdClass(),
            'type' => WorkflowStep::TYPE_START,
        ]);

//        return $workflow->fresh();
        return redirect(route('workflow.show', $workflow->id));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Workflow  $workflow
     * @return \Illuminate\Http\Response
     */
    public function show(Workflow $workflow)
    {
        \PageParams::put('body_class', 't-body loading');

//        \App\Models\User::class;
        $fields = [
            'User' => $this->describeUsersTable(),
            'UserFields' => $this->describeUserFields(),
        ];

        return view('workflow.show', ['workflow' => $workflow, 'fields' => $fields]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Workflow  $workflow
     * @return \Illuminate\Http\Response
     */
    public function edit(Workflow $workflow)
    {
        return view('workflow.edit', ['workflow' => $workflow]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Workflow  $workflow
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Workflow $workflow)
    {
        if ($request->get('main') && !$workflow->main) {
            Workflow::where('main', '=', '1')->update(['main' => 0]);
        }
        $workflow->update($request->all());
        return redirect(route('workflow.edit', $workflow->id));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Workflow  $workflow
     * @return \Illuminate\Http\Response
     */
    public function destroy(Workflow $workflow)
    {
        $workflow->delete();
        return response(['message' => 'Сценарий удален']);
    }

    public function step_path(Request $request, Workflow $workflow)
    {
        /** @var WorkflowStep[] $allSteps */
        $allSteps = $workflow->steps->keyBy('id');
        $proceeded_steps = [];
        $step = $request->all();

        $queue = [
            $step
        ];

        while($step = array_shift($queue)) {
            $proceeded_steps[$step['id']] = $step['id'];

            $allSteps[$step['id']]->update($step);
            foreach($step['next'] as $next_step) {
                array_push($queue, $next_step);
            }
        }

        // delete all records not in the path
        $allSteps->whereNotIn('id', $proceeded_steps)->each(function($model) {
            /** @var WorkflowStep $model */
            $model->delete();
        });
    }

    protected function describeUsersTable()
    {
        return [
            'name' => [
                'name' => 'Имя',
                'field_name' => 'name',
                'field_type' => 'string',
                'settings' => [
                    'length' => 255
                ],
            ],
            'last_name' => [
                'name' => 'Фамилия',
                'field_name' => 'last_name',
                'field_type' => 'string',
                'settings' => [
                    'length' => 255
                ],
            ],
            'email' => [
                'name' => 'Email',
                'field_name' => 'email',
                'field_type' => 'string',
                'settings' => [
                    'length' => 255
                ],
            ],
        ];
    }

    protected function describeUserFields()
    {
        return UserField::where('ref_table', 'users')->get()
            ->mapWithKeys(function ($field) {
                return [$field['field_name'] => $field];
            });
    }
}

resources/views/workflow/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        @if($workflow->exists)
                            Изменение сценария
                        @else
                            Добавление сценария
                        @endif
                    </div>
                    <div class="panel-body">
                        <form class="form-horizontal"
                              role="form" method="POST"
                              action="{{ $workflow->exists ? route('workflow.update', $workflow->id) : route('workflow.store') }}">
                            {{ csrf_field() }}
                            {{ $workflow->exists ? method_field('PUT') : "" }}

                            <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                                <label for="name" class="col-md-4 control-label">Название</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control" name="name" value="{{ old('name', $workflow->name) }}" required autofocus>

                                    @if ($errors->has('name'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-4">
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="main" value="1" {{ old('main', $workflow->main) ? 'checked' : '' }}>
                                            Основной <br>
                                            <span class="help-block">Основным может быть только 1 сценарий</span>
                                        </label>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        @if($workflow->exists)
                                            Изменить
                                        @else
                                            Добавить
                                        @endif
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/workflow/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Сценарии</div>
                    {{--<div class="panel-body"></div>--}}
                    <table class="table table-striped table-hover">
                        <tr>
                            <th width="50">ID</th>
                            <th>Название</th>
                            <th width="150"></th>
                        </tr>
                        @foreach($workflows as $item)
                            <tr id="workflow_{{ $item->id }}" class="{{ $item->active ? 'active' : '' }}">
                                <td>{{ $item->id }}</td>
                                <td><a href="{{ route('workflow.show', $item->id) }}">{{ $item->name }}</a></td>
                                <td>
                                    <a href="{{ route('workflow.edit', $item->id) }}"
                                       class="btn btn-xs btn-primary">изменить</a>
                                    <a href="{{ route('workflow.destroy', $item->id) }}"
                                       onclick="return postDelete(this, $('#workflow_{{ $item->id }}'))"
                                       class="btn btn-xs btn-danger">удалить</a>
                                </td>
                            </tr>
                        @endforeach
                        <tr>
                            <td colspan="3">
                                <a href="{{ route('workflow.create') }}" class="btn btn-primary">Добавить новый</a>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <script>
        function postDelete(link, deleteItem) {
            var url = $(link).attr('href');
            if (confirm('Уверены, что хотите удалить?')) {
                $.ajax({
                    url: url,
                    method: 'post',
                    dataType: 'json',
                    data: {
                        _method: 'delete'
                    }
                }).done(function (data) {
                    if (data.error) {
                        toastr.error(data.error);
                    } else {
                        toastr.info(data.message || 'Удалено');
                        if (deleteItem) {
                            if (!deleteItem.jquery) {
                                deleteItem = $(deleteItem);
                            }
                            deleteItem.remove();
                        }
                    }
                }).fail(function(xhr, status, error) {
                    toastr.error(error);
                });
            }
            return false;
        }
    </script>
@endsection

resources/views/workflow/show.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Lovelify | Настройка бота</title>
    <meta name="format-detection" content="telephone=no"/>
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon"/><!-- Assets -->
    <script src="/components/jquery/dist/jquery.min.js"></script>

    <link rel="stylesheet" href="/components/bootstrap/dist/css/bootstrap.min.css">
    {{--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">--}}
    <script src="/components/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="/assets/landing/js/jquery-1.10.2.min.js"></script>
</head>
@extends('layouts.app')

@section('content')
    <div id="wf-builder" class="wf-builder"></div>
@endsection

@push('scripts')
    {{--<script src="/assets/app.js"></script>--}}
    <script>
        (function(){
            var Love = window.Love = (window.Love || {});
            Love.Workflow = (Love.Workflow || {});
            Love.routes = {
                "section": {
                    "list": '{{  route('section.index') }}',
                },
                "assignment": {
                    "all": '{{  route('assignment.all') }}',
                    "list": '{{  route('section.assignment.index', ['section' => '_section_']) }}',
                    "show": '{{  route('section.assignment.show', ['section' => '_section_', 'assignment' => '_assignment_']) }}',
                },
                "workflow": {
                    "list": '{{  route('workflow.index') }}',
                    "show": '{{  route('workflow.show', $workflow->id) }}',
                    "step_path": '{{  route('workflow.step_path', $workflow->id) }}',
                    "steps": {
                        "list": '{{ route('workflow.steps.index', ['workflow' => $workflow->id]) }}',
                        "create": '{{ route('workflow.steps.store', ['workflow' => $workflow->id]) }}',
                        "update": '{{ route('workflow.steps.update', ['workflow' => $workflow->id, 'step' => '_step_']) }}',
                        "delete": '{{ route('workflow.steps.destroy', ['workflow' => $workflow->id, 'step' => '_step_']) }}',
                        "file": {
                            "upload": '{{  route('workflow.steps.file.upload', ['workflow' => $workflow->id, 'step' => '_step_']) }}',
                            "delete": '{{  route('workflow.steps.file.delete', ['workflow' => $workflow->id, 'step' => '_step_', 'file' => '_file_']) }}',
                        }
                    }
                }
            };
            Love.User = {!! \Auth::user()->toJson() !!};
            Love.Workflow.fields = {!! json_encode($fields) !!};
        })();
    </script>
@endpush

@if(App::environment('local'))
    @push('scripts')
        <script src="http://<?=request()->getHost()?>:8080/assets/app.min.js"></script>
    @endpush
@else
    @push('scripts')
        <script src="/assets/app.min.js"></script>
    @endpush
    @push('styles')
            <link rel="stylesheet" href="/assets/app.min.css">
    @endpush
@endif