routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Http\Request;


Route::get('/test2', "TelegramBotController@getUpdates");
Route::get('/test3', function (Request $request) {
    $user = \App\Models\User::where('email', 'putalexey@redlg.ru')->first();
    return response($user->getBotAddingUrl());
//    var_dump($_method->getDocComment());
//    var_dump(Telegram::sendMessage([
//        'chat_id' => 260019765,
//        'text' => 'test sending message'
//    ]));
});
Route::get('/test', function (Request $request) {
    echo "<form method='post'>
        " . csrf_field() . "
        <input type='submit' value='шаг'>
        </form>";

    echo "<div style='display: flex;'>";
        echo "<pre style='max-width: 50%;overflow: auto;'>";
        echo json_encode(
            \App\Models\ChatState::where('user_id', Auth::user()->id)
                ->without(['user', 'workflow.steps'])->first(),
                JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE
        );
        echo "</pre>";
        echo "<pre style='max-width: 50%;overflow: auto;'>";
        echo json_encode(
            \App\Models\ChatStatesHistory::where('user_id', Auth::user()->id)
                ->with(['chat', 'workflow', 'workflow_step'])
                ->without(['workflow.steps'])
                ->orderBy('id', 'desc')->limit(1)->offset(1)
                ->without(['workflow.steps'])->first(),
                JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE
        );
        echo "</pre>";
    echo "</div>";
});
Route::post('/test', function (Request $request) {
    \Carbon\Carbon::setTestNow(\Carbon\Carbon::now()->addDay());
//    $state = \App\Models\ChatState::where('chat_state', \App\Models\ChatState::STATE_STOPPED)->where('user_id', Auth::user()->id)->first();
    $state = \App\Models\ChatState::where('chat_state', "!=", \App\Models\ChatState::STATE_STOPPED)->where('user_id', Auth::user()->id)->first();
    if ($state)
        dispatch((new \App\Jobs\ProcessChatState($state))->onConnection('sync'));

    return back();
});
Route::get('/', function (Request $request) {
    $price = $request->get("option") == '09ea221d3db11df1f369094ffb4bda7c' ? '16900' : '9900';
    return view('landing', ["price" => $price]);
});
Route::any('/chat/', 'LandingChatController@index');
Route::get('/chat/email/', 'LandingChatController@getOurEmail');
Route::post('/chat/save/', 'LandingChatController@save');

// управление ботом
Route::group(['prefix' => 'bot'], function () {
    Route::post('webhook/{token}', 'TelegramBotController@webhook');
    Route::group(['middleware' => 'can:admin-bot'], function() {
        Route::get('/', 'TelegramBotController@index')->name('bot.index');
        Route::get('webhook', 'TelegramBotController@getWebhookInfo')->name('bot.webhook');
        Route::post('test', 'TelegramBotController@ping')->name('bot.ping');
        Route::post('init', 'TelegramBotController@sendCertificate')->name('bot.init');
    });
});


Auth::routes();
Route::group(["middleware" => 'auth' ], function() {
//    Route::get('/workflows/{workflow_id}/steps', "WorkflowController@steps");
    Route::get('/lk/', function (Request $request) {
        $sections = \App\Models\Section::ordered()
            ->with(['assignments', 'assignments.tasks'])
            ->get();
        $answers = \App\Models\TaskAnswer::where('user_id', Auth::user()->id)->get()->keyBy('task_id');
        return view('cabinet.assignments', [
            "sections" => $sections,
            "answers" => $answers,
        ]);
    })->name('cabinet');
    Route::put('workflow/{workflow}/step_path', "WorkflowController@step_path")->name('workflow.step_path');
    Route::post('workflow/{workflow}/steps/{step}/file', "WorkflowStepsController@uploadFile")->name('workflow.steps.file.upload');
    Route::delete('workflow/{workflow}/steps/{step}/file/{file}', "WorkflowStepsController@deleteFile")->name('workflow.steps.file.delete');

    Route::get('assignment', "AssignmentController@all")->name('assignment.all');
    Route::resource('section', "SectionController");
    Route::resource('section.assignment', "AssignmentController");
    Route::resource('section.assignment.task', "TaskController");

    Route::resource('workflow', "WorkflowController");
    Route::resource('workflow.steps', "WorkflowStepsController", [
        'except' => ['create', 'show', 'edit',]
    ]);
});

Route::get('/home', 'HomeController@index');

app/Models/Assignment.php
<?php

namespace App\Models;

use App\Traits\UpdatesPositions;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Assignment
 *
 * @package App\Models
 * @property int $id
 * @property string $name
 * @property string $description
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @property string $video
 * @property int $position
 * @property int $section_id
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Assignment whereCreatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Assignment whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Assignment whereName($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Assignment wherePosition($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Assignment whereSectionId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Assignment whereUpdatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Assignment whereVideo($value)
 * @mixin \Eloquent
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Assignment ordered()
 * @property-read \App\Models\Section $section
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Task[] $tasks
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Assignment whereDescription($value)
 */
class Assignment extends Model
{
    use UpdatesPositions;

    protected $attributes = [
        'position' => 0,
    ];

    protected $fillable = [
        'name',
        'video',
        'description',
        'position',
        'section_id',
    ];

    public function scopeOrdered($query) {
        return $query->orderBy('position');
    }

    public function section()
    {
        return $this->belongsTo(Section::class);
    }
    public function tasks()
    {
        return $this->hasMany(Task::class);
    }
}

app/Http/Controllers/AssignmentController.php
<?php

namespace App\Http\Controllers;

use App\Traits\GeneratesSelectPositions;
use App\Models\Assignment;
use App\Models\Section;
use Illuminate\Http\Request;

class AssignmentController extends Controller
{
    use GeneratesSelectPositions;

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function all(Request $request)
    {
        $assignments = Assignment::orderBy('section_id')->ordered()->get();

        return $assignments;
    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @param Section $section
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request, Section $section)
    {
        $assignments = $section->assignments()->ordered()->get();
        if ($request->expectsJson()) {
            return $assignments;
        }
        return view('assignment.index', ['assignments' => $assignments, 'section' => $section]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Section $section)
    {
        $assignment = new Assignment();

        $select_positions = $this->getSelectPositions($section->assignments()->ordered()->get(), $assignment);
        $section->position = $select_positions->keys()->last();
        return view('assignment.edit', [
            'assignment' => $assignment,
            'sections' => Section::ordered()->get(),
            'select_positions' => $select_positions,
            'section' => $section
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param int $section_id
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $section_id)
    {
        $this->validate($request, $this->getValidationRules());
        $assignment = Assignment::create($request->only([
            'name', 'video', 'position', 'section_id', 'description',
        ]));
        Assignment::updatePositions($assignment->section_id);

        return redirect(route('section.assignment.index', [$section_id]));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Assignment  $assignment
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, Section $section, Assignment $assignment)
    {
        if ($request->expectsJson()) {
            return $assignment;
        }
        return redirect(route('section.assignment.edit', [$section->id, $assignment->id]));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Assignment  $assignment
     * @return \Illuminate\Http\Response
     */
    public function edit(Section $section, Assignment $assignment)
    {
        return view('assignment.edit', [
            'assignment' => $assignment,
            'sections' => Section::ordered()->get(),
            'select_positions' => $this->getSelectPositions(
                $section->assignments()->ordered()->get(),
                $assignment
            ),
            'section' => $section
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param int $section_id
     * @param  \App\Models\Assignment $assignment
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $section_id, Assignment $assignment)
    {
        $this->validate($request, $this->getValidationRules());
        $assignment->update($request->only([
            'name', 'video', 'position', 'section_id', 'description',
        ]));
        Assignment::updatePositions($section_id);
        return redirect(route('section.assignment.index', [$section_id]));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Assignment  $assignment
     * @return \Illuminate\Http\Response
     */
    public function destroy($section_id, Assignment $assignment)
    {
        $assignment->delete();

        return redirect(route('section.assignment.index', [$section_id]));
    }

    protected function getValidationRules() {
        return [
            'name' => 'required|max:255',
            'video' => 'max:512',
            'position' => 'integer',
            'section_id' => 'integer',
        ];
    }
}

resources/views/assignment/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <a href="{{ route('section.assignment.index', [$section->id]) }}" class="btn-link">← К списку</a>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        @if($assignment->exists)
                            Изменение упражнения
                        @else
                            Добавление упражнения
                        @endif
                    </div>
                    <div class="panel-body">
                        <form class="form-horizontal"
                              role="form" method="POST"
                              action="{{ $assignment->exists ? route('section.assignment.update', [$section->id, $assignment->id]) : route('section.assignment.store', $section->id) }}">
                            {{ csrf_field() }}
                            {{ $assignment->exists ? method_field('PUT') : "" }}
                            <input type="hidden" name="section_id" value="{{ $section->id }}">

                            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                                <label for="name" class="col-md-4 control-label">Название</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control" name="name" value="{{ old('name', $assignment->name) }}" required autofocus>

                                    @if ($errors->has('name'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                                <label for="description" class="col-md-4 control-label">Описание</label>
                                <div class="col-md-6">
                                    <textarea id="description" name="description" class="form-control">{{ old('description', $assignment->description) }}</textarea>
                                    @if ($errors->has('description'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('video') ? ' has-error' : '' }}">
                                <label for="video" class="col-md-4 control-label">Видео (ссылка)</label>
                                <div class="col-md-6">
                                    <input id="video" type="text" name="video" value="{{ old('video', $assignment->video) }}" class="form-control">
                                    @if ($errors->has('video'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('video') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            {{--<div class="form-group{{ $errors->has('position') ? ' has-error' : '' }}">
                                <label for="position" class="col-md-4 control-label">Порядок</label>

                                <div class="col-md-6">
                                    <input id="position" type="text" name="position" value="{{ old('position', $assignment->position) }}" class="form-control">
                                    @if ($errors->has('position'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('position') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>--}}

                            <div class="form-group{{ $errors->has('position') ? ' has-error' : '' }}">
                                <label for="position" class="col-md-4 control-label">Порядок</label>
                                <div class="col-md-6">
                                    {{ \Form::select('position', $select_positions, old('position', $assignment->position), ['class' => 'form-control']) }}
                                    @if ($errors->has('position'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('position') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        @if($assignment->exists)
                                            Измененить
                                        @else
                                            Добавить
                                        @endif
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/assignment/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <a href="{{ route('section.index') }}" class="btn-link">← К разделам</a>
                <div class="panel panel-default">
                    <div class="panel-heading">Упражнения раздела "{{ $section->name }}"</div>
                    {{--<div class="panel-body"></div>--}}
                    <table class="table table-striped table-hover">
                        <tr>
                            <th width="50">ID</th>
                            <th>Название</th>
                            <th>Порядок</th>
                            <th width="250"></th>
                        </tr>
                        @foreach($assignments as $item)
                            <tr id="assignment_{{ $item->id }}" class="{{ $item->active ? 'active' : '' }}">
                                <td>{{ $item->id }}</td>
                                <td><a href="{{ route('section.assignment.edit', [$section->id, $item->id]) }}">{{ $item->name }}</a></td>
                                <td>{{ $item->position }}</td>
                                <td>
                                    <a href="{{ route('section.assignment.task.index', [$section->id, $item->id]) }}"
                                       class="btn btn-xs btn-primary">задания</a>
                                    <a href="{{ route('section.assignment.edit', [$section->id, $item->id]) }}"
                                       class="btn btn-xs btn-primary">изменить</a>
                                    <a href="{{ route('section.assignment.destroy', [$section->id, $item->id]) }}"
                                       onclick="return postDelete(this, $('#assignment_{{ $item->id }}'))"
                                       class="btn btn-xs btn-danger">удалить</a>
                                </td>
                            </tr>
                        @endforeach
                        <tr>
                            <td colspan="4">
                                <a href="{{ route('section.assignment.create', [$section->id]) }}" class="btn btn-primary">Добавить новый</a>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <script>
        function postDelete(link, deleteItem) {
            var url = $(link).attr('href');
            if (confirm('Уверены, что хотите удалить?')) {
                $.ajax({
                    url: url,
                    method: 'post',
                    dataType: 'json',
                    data: {
                        _method: 'delete'
                    }
                }).done(function (data) {
                    if (data.error) {
                        toastr.error(data.error);
                    } else {
                        toastr.info(data.message || 'Удалено');
                        if (deleteItem) {
                            if (!deleteItem.jquery) {
                                deleteItem = $(deleteItem);
                            }
                            deleteItem.remove();
                        }
                    }
                }).fail(function(xhr, status, error) {
                    toastr.error(error);
                });
            }
            return false;
        }
    </script>
@endsection